columnSuffix: null
handle: servings
instructions: null
name: Servings
searchable: false
settings:
  decimals: 1
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
